### ISSUE TITLE
Docs: Add CONTRIBUTING.MD

### ISSUE THREAD

**Issue by Boursler** [HOMS-OSS/perf-rust#24]
Describe project workflow and include checklist for everyone to refer to.

**Comment by Sl1mb0** [comment]
Here are my ideas: 

* Minimum one person other than yourself must review code. For major changes, whole team must review so that everyone is up to speed.
 * Must rebase & merge yourself.
 * `cargo fmt` and `cargo clippy` must pass.
 * All sources files are well-documented, specifically:
   * There must be a high-level brief providing a description at the top of the file
   * Data structures and their methods must be provided brief description as well.
